# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'kadai10_Firestore' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for kadai10_Firestore
pod 'Firebase/Firestore'
pod 'FirebaseFirestoreSwift'
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'GoogleSignIn'
pod 'FBSDKLoginKit'
pod 'PKHUD', '~> 5.0


end
